import { defineConfig } from 'vite';
import react from '@vitejs/plugin-react';
import { VitePWA } from 'vite-plugin-pwa';

// https://vitejs.dev/config/
export default defineConfig(({ mode }) => {
  const isCapacitorBuild = mode === 'capacitor';
  const base = isCapacitorBuild ? './' : '/TrackIndexes/';
  const startUrl = isCapacitorBuild ? './' : '/TrackIndexes/';

  return {
    base,
    plugins: [
      react(),
      VitePWA({
        registerType: 'autoUpdate',
        includeAssets: ['icons/*.png', 'icons/*.svg'],
        devOptions: {
          enabled: true,
        },
        manifest: {
          name: 'TrackIndexes',
          short_name: 'TrackIdx',
          description: 'Quick-glance tracker for major Indian market indexes.',
          theme_color: '#1e293b',
          background_color: '#0f172a',
          display: 'standalone',
          start_url: startUrl,
          icons: [
            {
              src: 'icons/icon-192.png',
              sizes: '192x192',
              type: 'image/png',
            },
            {
              src: 'icons/icon-512.png',
              sizes: '512x512',
              type: 'image/png',
            },
            {
              src: 'icons/icon-512.png',
              sizes: '512x512',
              type: 'image/png',
              purpose: 'any maskable',
            },
          ],
        },
        workbox: {
          // Precache all static assets generated by Vite
          globPatterns: ['**/*.{js,css,html,ico,png,svg,woff2}'],
          navigateFallback: 'index.html',
          runtimeCaching: [
            {
              // Cache Yahoo Finance API responses with StaleWhileRevalidate
              urlPattern: /query1\.finance\.yahoo\.com\/v7\/finance\/quote/,
              handler: 'StaleWhileRevalidate',
              options: {
                cacheName: 'market-data-cache',
                expiration: {
                  maxEntries: 50,
                  maxAgeSeconds: 5 * 60, // 5 minutes
                },
                cacheableResponse: {
                  statuses: [0, 200],
                },
              },
            },
          ],
        },
      }),
    ],
  };
});
